# Generated by Django 5.0.6 on 2024-06-19 19:49

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.CharField(max_length=10, validators=[utils.validators.only_int])),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
