# Generated by Django 5.0.6 on 2024-06-19 22:48

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_ID',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[utils.validators.only_int]),
        ),
    ]
