# Generated by Django 5.0.6 on 2024-06-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_ID',
            field=models.CharField(max_length=10),
        ),
    ]
